#items considered as shield
#example: minecraft:bow
shield_items = []
#items considered as bow
#example: minecraft:bow
bow_items = ["alexscaves:dreadbow", "cataclysm:void_assault_shoulder_weapon", "cataclysm:wither_assault_shoulder_weapon", "cataclysm:laser_gatling", "cataclysm:meat_shredder"]
#items considered as crossbow
#example: minecraft:bow
crossbow_items = []
#items considered as trident
#example: minecraft:bow
trident_items = []
#items considered as katana
#example: minecraft:bow 0
katana_items = []

