
[default_gamerule]
	doVanillaAttack = true
	globalStun = true
	keepSkills = true
	hasFallAnimation = true
	disapleEntityUI = false
	stiffComboAttacks = true
	#Range: 0 ~ 100
	weightPenalty = 5
	canSwitchCombat = true
	noMobsInBossfight = true

[loot]
	#Range: -100 ~ 100
	skill_book_mob_drop_chance_modifier = 0
	#Range: -100 ~ 100
	skill_book_chest_drop_chance_modifier = 0

