
["Mob Effects"]
	#Enable/Disable mob stun (!Warning! Disabling this function may make this mob way easier to beat)
	"Allow Withered Abomination Stun" = true

	["Mob Effects"."Overgrown Colosuss"]
		#Enable/Disable mob stun (!Warning! Disabling this function may make this mob way easier to beat)
		"Allow Overgrown Colosuss stun" = true

	["Mob Effects"."Ancient Guardian"]
		#Enable/Disable mob stun (!Warning! Disabling this function may make this mob way easier to beat)
		"Allow Ancient Guardian stun" = true

	["Mob Effects"."Posessed Paladin"]
		#Enable/Disable mob stun (!Warning! Disabling this function may make this mob way easier to beat)
		"Allow Posessed Paladin stun" = true

	["Mob Effects"."Cloud Golem's Falling Cloud"]
		#Enable/Disable mob stun (!Warning! Disabling this function may make Cloud Golem mob way easier to beat)
		"Allow Cloud Golem's Falling Cloud Stun" = true

[Multipliers]
	#Multiplies damage for every mob
	#Range: 1.0 ~ 100.0
	"Mob Damage Multiplier" = 1.0
	#Multiplies health for every mob
	#Range: 1.0 ~ 100.0
	"Mob Health Multiplier" = 2.0

["Mob Settings"]

	["Mob Settings"."Posessed Paladin Settings"]
		#Set the damage dealt by Posessed Paladin
		#Range: 13.0 ~ 100.0
		"Posessed Paladin Damage" = 16.0
		#Set the health of Posessed Paladin
		#Range: 150.0 ~ 1000.0
		"Posessed Paladin Health" = 170.0

	["Mob Settings"."Haunted Guard Settings"]
		#Set the damage dealt by Haunted Guard
		#Range: 8.0 ~ 100.0
		"Haunted Guard Damage" = 11.0
		#Set the health of Haunted Guard
		#Range: 30.0 ~ 1000.0
		"Haunted Guard Health" = 35.0

	["Mob Settings"."Haunted Knight Settings"]
		#Set the damage dealt by Haunted Guard
		#Range: 8.0 ~ 100.0
		"Haunted Knight Damage" = 11.0
		#Set the health of Haunted Knight
		#Range: 30.0 ~ 1000.0
		"Haunted Knight Health" = 37.0

	["Mob Settings"."Ancient Guardian Settings"]
		#Set the damage dealt by Ancient Guardian
		#Range: 17.0 ~ 100.0
		"Ancient Guardian Damage" = 20.0
		#Set the health of Ancient Guardian
		#Range: 150.0 ~ 1000.0
		"Ancient Guardian Health" = 170.0

	["Mob Settings"."Ambusher Settings"]
		#Set the damage dealt by Ambusher
		#Range: 5.0 ~ 100.0
		"Ambusher Damage" = 8.0
		#Set the health of Ambusher
		#Range: 30.0 ~ 1000.0
		"Ambusher Health" = 50.0

	["Mob Settings"."Spiky Worm Settings"]
		#Set the damage dealt by Spiky Worm
		#Range: 1.0 ~ 100.0
		"Spiky Worm Damage" = 3.0
		#Set the health of Spiky Worm
		#Range: 5.0 ~ 1000.0
		"Spiky Worm Health" = 15.0

	["Mob Settings"."Cloud Golem (Phase 1) Settings"]
		#Set the health of Cloud Golem (Phase 1)
		#Range: 70.0 ~ 1000.0
		"Cloud Golem (Phase 1) Health" = 100.0

	["Mob Settings"."Cloud Golem (Phase 2) Settings"]
		#Set the damage dealt by Cloud Golem (Phase 2)
		#Range: 12.0 ~ 100.0
		"Cloud Golem (Phase 2) Damage" = 15.0
		#Set the health of Cloud Golem (Phase 2)
		#Range: 70.0 ~ 1000.0
		"Cloud Golem (Phase 2) Health" = 100.0

	["Mob Settings"."Overgrown Colosuss Settings"]
		#Set the damage dealt by Overgrown Colosuss
		#Range: 12.0 ~ 100.0
		"Overgrown Colosuss Damage" = 16.0
		#Set the health of Overgrown Colosuss
		#Range: 150.0 ~ 1000.0
		"Overgrown Colosuss Health" = 170.0

	["Mob Settings"."Frostbitten Golem Settings"]
		#Set the damage dealt by Frostbitten Golem
		#Range: 11.0 ~ 100.0
		"Frostbitten Golem Damage" = 16.0
		#Set the health of Frostbitten Golem
		#Range: 150.0 ~ 1000.0
		"Frostbitten Golem Health" = 170.0

	["Mob Settings"."Lava Eater Settings"]
		#Set the damage dealt by Lava Eater
		#Range: 7.0 ~ 100.0
		"Lava Eater Damage" = 12.0
		#Set the health of Lava Eater
		#Range: 120.0 ~ 1000.0
		"Lava Eater Health" = 150.0

	["Mob Settings"."Shulker Mimic Settings"]
		#Set the damage dealt by Shulker Mimic
		#Range: 8.0 ~ 100.0
		"Shulker Mimic Damage" = 12.0
		#Set the health of Shulker Mimic
		#Range: 120.0 ~ 1000.0
		"Shulker Mimic Health" = 150.0

	["Mob Settings"."Skeletosaurus Settings"]
		#Set the damage dealt by Skeletosaurus
		#Range: 6.0 ~ 100.0
		"Skeletosaurus Damage" = 13.0
		#Set the health of Skeletosaurus
		#Range: 120.0 ~ 1000.0
		"Skeletosaurus Health" = 150.0

	["Mob Settings"."Withered Abomination Settings"]
		#Set the damage dealt by Withered Abomination
		#Range: 12.0 ~ 100.0
		"Withered Abomination Damage" = 15.5
		#Set the health of Withered Abomination
		#Range: 160.0 ~ 1000.0
		"Withered Abomination Health" = 190.0

	["Mob Settings"."Endersent Settings"]
		#Set the damage dealt by Endersent
		#Range: 12.0 ~ 100.0
		"Endersent Damage" = 16.0
		#Set the health of Endersent
		#Range: 160.0 ~ 1000.0
		"Endersent Health" = 200.0

	["Mob Settings"."Chorusling Settings"]
		#Set the damage dealt by Chorusling
		#Range: 5.0 ~ 100.0
		"Chorusling Damage" = 6.0
		#Set the health of Chorusling
		#Range: 40.0 ~ 1000.0
		"Chorusling Health" = 70.0

	["Mob Settings"."Warped Fungussus Settings"]
		#Set the damage dealt by Warped Fungussus
		#Range: 5.0 ~ 100.0
		"Warped Fungussus Damage" = 7.0
		#Set the health of Warped Fungussus
		#Range: 70.0 ~ 1000.0
		"Warped Fungussus Health" = 100.0

	["Mob Settings"."Mossy Golem Settings"]
		#Set the damage dealt by Mossy Golem
		#Range: 3.0 ~ 100.0
		"Mossy Golem Damage" = 5.0
		#Set the health of Mossy Golem
		#Range: 20.0 ~ 1000.0
		"Mossy Golem Health" = 25.0

	["Mob Settings"."Dune Sentinel Settings"]
		#Set the health of Dune Sentinel
		#Range: 120.0 ~ 1000.0
		"Dune Sentinel Health" = 170.0

